
#define TYPE @"type"
#define COLOR @"color"
#define WHITE @"white"
#define BLACK @"black"
#define PLAYER_COLOR @"player_color"
#define PIECES_SETUP @"pieces_setup"
#define X_LOCATION @"x"
#define Y_LOCATION @"y"
#define START_X @"start_x"
#define START_Y @"start_y"
#define FINISH_X @"finish_x"
#define FINISH_Y @"finish_y"
#define MOVES @"moves"
#define COMPUTER_MOVE_FIRST @"computer_move_first"